### ISSUE TITLE
When rolldown handles external modules,it should replace the source in the ImportDeclaration with oxc-resolver to return the result in the error

### ISSUE THREAD

**Issue by zhusjfaker** [rolldown/rolldown#1185]
in  esbuild repo 

https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_packagejson_test.go#L2878

in rolldown esbuild test package_json case

https://github.com/rolldown/rolldown/tree/main/crates/rolldown/tests/esbuild/packagejson/.test_package_json_subpath_import_node_builtin_issue3485

oxc-resolver test unit case
```rust
   #[test]
    fn test_resolver_package_json_bad_main() {
        let options = ResolveOptions {
            alias_fields: vec![vec!["browser".into()]],
            exports_fields: vec![vec!["exports".into()]],
            condition_names: vec!["node".into(), "import".into(), "require".into()],
            main_fields: vec!["main".into()],
            // alias: vec![("#fs".into(),vec!["fs".into()] ), ("#http".into(),vec![ "node:http".into()])],
            ..ResolveOptions::default()
        };
        let dir = Path::new("/Users/jason.zhu/Desktop/github/rolldown/crates/rolldown/tests/esbuild/packagejson/test_package_json_subpath_import_node_builtin_issue3485");
        let resolver = Resolver::new(options);
        let res = resolver.resolve(dir, "#http").unwrap();
        println!("res-> \n {:#?}", res);
    }
```

terminal output
```sh
failures:

---- tests::test_resolver_package_json_bad_main stdout ----
thread 'tests::test_resolver_package_json_bad_main' panicked at tests/mod.rs:90:50:
called `Result::unwrap()` on an `Err` value: NotFound("node:http")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: mod::tests::test_resolver_package_json_bad_main
             at ./tests/mod.rs:90:19
   5: mod::tests::test_resolver_package_json_bad_main::{{closure}}
             at ./tests/mod.rs:79:45
   6: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

In the result,it can clearly see that oxc-resolver has converted #http to node:http based on the imports field.

I personally suggest that you need to compare whether the source in ast is consistent with the returned result, and if not, you need to replace it with the result of the resolver.

rolldown current result 

entry.mjs
```js
// do not replace the imports fileds
import { default as fs } from "#fs";
import { default as http } from "#http";

// entry.js
fs.readFileSync();
http.createServer();

```

**Comment by hyf0** [comment]
I have something in mind to fix this. It requires to change the core code a little bit and I'm thinking how to apply the fix.

**Comment by hyf0** [comment]
Need to wait for https://github.com/oxc-project/oxc-resolver/issues/164.
