### ISSUE TITLE
Throw an warning if passed `tsconfigFilename` not exist

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1444]
Probably should check if the path exist and give a warning about if the file is not existed in rolldown's side.

_Originally posted by @hyf0 in https://github.com/rolldown/rolldown/pull/1442#discussion_r1653862730_

**Comment by hyf0** [comment]
I remember the `oxc_resolver` has a `TsconfigNotFound` error. Should investigate why

> the other strange thing is that the tsconfig file is successfully found and read, there is no TsconfigNotFound error https://github.com/rolldown/rolldown/issues/1441

**Comment by hi-ogawa** [comment]
It looks like `TsconfigNotFound` error surfaces correctly now. https://stackblitz.com/edit/github-ghiuud?file=rolldown.config.mjs

```ts
import { defineConfig } from 'rolldown';

export default defineConfig({
  input: ['./src/entry.js', './src/other-entry.js'],
  resolve: {
    tsconfigFilename: 'not-exist.json',
  },
});
```

```
 ERROR  Rolldown internal error: Tsconfig not found /home/projects/xoriwgqxmv.github/not-exist.json          6:41:29 PM

  at napi_create_error (node_modules/@emnapi/core/dist/emnapi-core.cjs.js:4464:25)
  at eval (node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1283:58)
  at NodeEnv.callIntoModule (node_modules/@emnapi/runtime/dist/emnapi.cjs.js:659:19)
  at NodeEnv.callbackIntoModule (node_modules/@emnapi/runtime/dist/emnapi.cjs.js:787:21)
  at f (node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1277:37)
  at Object.dispatchOne (node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1305:29)
  at Object.dispatch (node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1321:43)
  at Worker.handler (node_modules/@emnapi/core/dist/emnapi-core.cjs.js:864:40) 
```

Should this be only a warning instead of error? I think getting a hard error seems reasonable though.
