### ISSUE TITLE
Tracking: esbuild/tests/bundler_ts failed tests

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1513]
## enum_rules_from_type_script_5_0

```bash
 called `Result::unwrap()` on an `Err` value: Parse failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Expected `,` but found `Identifier`",
            labels: Some(
                [
                    LabeledSpan {
                        label: Some(
                            "`,` expected",
                        ),
                        span: SourceSpan {
                            offset: SourceOffset(
                                877,
                            ),
                            length: 2,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Error,
        },
    },
]
```

## export_type_issue379

```bash
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:67:21:
no entry found for key
```

## this_inside_function_ts

- not lower syntax

## this_inside_function_ts_no_bundle

- not lower syntax

## this_inside_function_ts_no_bundle_use_define_for_class_fields

- not lower syntax

## this_inside_function_ts_use_define_for_class_fields

- not lower syntax

## ts_abstract_class_field_use_assign

- snapshot not matched

## ts_common_js_variable_in_esm_type_module

- snapshot not matched

## ts_computed_class_field_use_define_false

- not lower syntax

## ts_computed_class_field_use_define_true

- not lower syntax

## ts_computed_class_field_use_define_true_lower

- not lower syntax

## ts_const_enum_comments

- snapshot not matched, esbuild would inline the enum value.

## ts_declare_class

- passed

## ts_declare_class_fields

- not lowe syntax

## ts_declare_const

- passed

## ts_declare_const_enum

- passed

## ts_declare_enum

- passed

## ts_declare_function

- passed

## ts_declare_let

- passed

## ts_declare_namespace

- passed

## ts_declare_var

- passed

## ts_enum_cross_module_inlining_access

- esbuild would generate **Pure** annotation
- esbuild would inline enum value.

## ts_enum_cross_module_inlining_definitions

- esbuild would generate **Pure** annotation
- esbuild would inline enum value.

## ts_enum_cross_module_inlining_minify_index_into_dot

- esbuild would inline enum value.

## ts_enum_cross_module_inlining_re_export

- esbuild would inline enum value.

## ts_enum_cross_module_tree_shaking

- esbuild would generate **Pure** annotation
- esbuild would inline enum value.

## ts_enum_define

- esbuild would generate **Pure** annotation

## ts_enum_export_clause

-  esbuild would inline enum value.

## ts_enum_jsx

- esbuild would generate **Pure** annotation
- esbuild would inline enum value.

## ts_enum_same_module_inlining_access

- esbuild would generate **Pure** annotation
- esbuild would inline enum value.

## ts_enum_tree_shaking

- esbuild would generate **Pure** annotation
- esbuild would inline enum value.

## ts_enum_use_before_declare
- esbuild would generate **Pure** annotation
- esbuild would inline enum value.
- 
## ts_experimental_decorator_scope_issue2147

- snapshot not matched

## ts_experimental_decorators

```bash
called `Result::unwrap()` on an `Err` value: Parse failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Optional chaining cannot appear in the callee of new expressions",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                17,
                            ),
                            length: 5,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Error,
        },
    },
]

```

## ts_experimental_decorators_keep_names

- not lower syntax

## ts_experimental_decorators_mangle_props_assign_semantics

- snapshot not matched

## ts_experimental_decorators_mangle_props_define_semantics

- snapshot not matched

## ts_experimental_decorators_mangle_props_methods

- snapshot not match

## ts_experimental_decorators_mangle_props_static_assign_semantics

- snapshot not match

## ts_experimental_decorators_mangle_props_static_define_semantics

- snapshot not match

## ts_experimental_decorators_mangle_props_static_methods

- snapshot not match

## ts_experimental_decorators_no_config

```bash
Symbol "y" in ResourceId("/Documents/rolldown-rs/rolldown/crates/rolldown/tests/esbuild/bundler_ts/ts_experimental_decorators_no_config/entry.ts") should belong to a chunk
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

## ts_export_default_type_issue316

```bash
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                28,
                            ),
                            length: 7,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },

```

## ts_export_equals

```bash
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                28,
                            ),
                            length: 7,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },

```

## ts_export_missing_es6

```bash
expected success, but got errors: [BuildError { inner: MissingExport { stable_importer: "foo.ts", stable_importee: "bar.js", importer_source: "export {nope} from './bar'", imported_specifier: "nope", im
ported_specifier_span: Span { start: 8, end: 12 } }, source: None, severity: Error }]

```

## ts_export_namespace

```bash
called `Result::unwrap()` on an `Err` value: Transform failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                55,
                            ),
                            length: 7,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                100,
                            ),
                            length: 7,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },
]

```

## ts_implicit_extensions

- runtime error , can't found module

ts_implicit_extensions_missing
ts_import_cts
ts_import_empty_namespace

## ts_import_equals_bundle

- after oxc transpile there is no way to tree shake, `unused` variable.
- esbuild would generate same output https://esbuild.github.io/try/#YgAwLjIwLjIAewogIGJ1bmRsZTogdHJ1ZSwKICBtaW5pZnk6IGZhbHNlLAogIGZvcm1hdDogJ2VzbScsCiAgZXh0ZXJuYWw6IFsicGtnIl0KfQBlAGVudHJ5LmpzAGltcG9ydCB7IGZvbyB9IGZyb20gInBrZyI7CnZhciB1c2VkID0gZm9vLnVzZWQ7CnZhciB1bnVzZWQgPSBmb28udW51c2VkOwoKZXhwb3J0IHsKICB1c2VkCn07AABmaWxlLmpzAHZhciB2ID0gdHlwZW9mIGxvY2FsVmFyCm1vZHVsZS5leHBvcnRzID0gdg

## ts_import_equals_elimination_test

-  after oxc transpile there is no way to tree shake, `unused` variable.

## ts_import_equals_tree_shaking_false

-  the interesting thing is esbuild would eliminate unused variable even the `treeshake` is `false`

## ts_import_equals_tree_shaking_true

-  after oxc transpile there is no way to tree shake, `unused` variable.

## ts_import_equals_undefined_import

- snapshot not matched.

## ts_import_missing_es6

```bash
called `Result::unwrap()` on an `Err` value: Transform failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                55,
                            ),
                            length: 7,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                100,
                            ),
                            length: 7,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },
]

```

## ts_import_missing_file

- We should emit Error rather than generate a bundle.

## ts_import_missing_unused_es6

- snapshot notmatched

## ts_import_mts

```bash
node:internal/modules/esm/resolve:265
    throw new ERR_MODULE_NOT_FOUND(
          ^

```

## ts_import_type_only_file

- passed

## ts_import_vs_local_collision_all_types

- runtime error, missing modules

## ts_import_vs_local_collision_mixed

```bash
thread 'test_tests__esbuild__bundler_ts__ts_import_vs_local_collision_mixed__config_json' panicked at crates/rolldown/tests/common/case.rs:35:7:
expected success, but got errors: [BuildError { inner: MissingExport { stable_importer: "entry.ts", stable_importee: "other.ts", importer_source: "import {a, b, c, d, e, real} from './other.ts'\nlet a\n
const b = 0\nvar c\nfunction d() {}\nclass e {}\nconsole.log(a, b, c, d, e, real)", imported_specifier: "c", imported_specifier_span: Span { start: 14, end: 15 } }, source: None, severity: Error }, Buil
dError { inner: MissingExport { stable_importer: "entry.ts", stable_importee: "other.ts", importer_source: "import {a, b, c, d, e, real} from './other.ts'\nlet a\nconst b = 0\nvar c\nfunction d() {}\ncl
ass e {}\nconsole.log(a, b, c, d, e, real)", imported_specifier: "b", imported_specifier_span: Span { start: 11, end: 12 } }, source: None, severity: Error }, BuildError { inner: MissingExport { stable_
importer: "entry.ts", stable_importee: "other.ts", importer_source: "import {a, b, c, d, e, real} from './other.ts'\nlet a\nconst b = 0\nvar c\nfunction d() {}\nclass e {}\nconsole.log(a, b, c, d, e, re
al)", imported_specifier: "a", imported_specifier_span: Span { start: 8, end: 9 } }, source: None, severity: Error }, BuildError { inner: MissingExport { stable_importer: "entry.ts", stable_importee: "o
ther.ts", importer_source: "import {a, b, c, d, e, real} from './other.ts'\nlet a\nconst b = 0\nvar c\nfunction d() {}\nclass e {}\nconsole.log(a, b, c, d, e, real)", imported_specifier: "d", imported_s
pecifier_span: Span { start: 17, end: 18 } }, source: None, severity: Error }, BuildError { inner: MissingExport { stable_importer: "entry.ts", stable_importee: "other.ts", importer_source: "import {a, 
b, c, d, e, real} from './other.ts'\nlet a\nconst b = 0\nvar c\nfunction d() {}\nclass e {}\nconsole.log(a, b, c, d, e, real)", imported_specifier: "e", imported_specifier_span: Span { start: 20, end: 2
1 } }, source: None, severity: Error }]

```

## ts_minified_bundle_common_js

- snapshot not matched

## ts_minified_bundle_es6

- snapshot not matched

## ts_minify_derived_class

- snapshot not matched

## ts_minify_enum

- snapshot not matched

## ts_minify_enum_cross_file_inline_strings_into_templates

```bash
called `Result::unwrap()` on an `Err` value: Parse failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Unterminated string",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                105,
                            ),
                            length: 6,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Error,
        },
    },
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Expected `,` but found `Unknown`",
            labels: Some(
                [
                    LabeledSpan {
                        label: Some(
                            "`,` expected",
                        ),
                        span: SourceSpan {
                            offset: SourceOffset(
                                105,
                            ),
                            length: 6,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Error,
        },
    },
]

```

## ts_minify_enum_property_names

```bash
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/ast_scanner/mod.rs:376:44:
must have reference id

```

## ts_minify_namespace

```bash
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/ast_scanner/impl_visit.rsthread ':tokio-runtime-worker35' panicked at :/Documents/rolldown-rs/rolldown/crates/rolldown_oxc_uti
ls/src/ext/mod.rs43::
21called `Option::unwrap()` on a `None` value:
44:
fail get symbol id from BindingIdentifier { span: Span { start: 0, end: 0 }, name: "Foo", symbol_id: Cell { value: None } }

```

## ts_minify_namespace_no_arrow

```bash
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at ' panicked at /Documents/rolldown-rs/rolldown/crates/rolldown_oxc_utils/src/ext/mod.rscrates/rolldown/src/ast_scanner/im
pl_visit.rs::2135::4443:
:
fail get symbol id from BindingIdentifier { span: Span { start: 0, end: 0 }, name: "Foo", symbol_id: Cell { value: None } }called `Option::unwrap()` on a `None` value

```

## ts_minify_namespace_no_logical_assignment

```bash
thread 'tokio-runtime-worker' panicked at /Documents/rolldown-rs/rolldown/crates/rolldown_oxc_utils/src/ext/mod.rs:21:44:
fail get symbol id from BindingIdentifier { span: Span { start: 0, end: 0 }, name: "Foo", symbol_id: Cell { value: None } }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/ast_scanner/impl_visit.rs:35:43:

```

## ts_minify_nested_enum

```bash
tokio-runtime-worker' panicked at crates/rolldown/src/ast_scanner/mod.rs:376:44:
must have reference id

```

## ts_minify_nested_enum_no_arrow

```bash
thread 'thread 'tokio-runtime-worker' panicked at tokio-runtime-workercrates/rolldown/src/ast_scanner/mod.rs' panicked at :crates/rolldown/src/ast_scanner/mod.rs376::37644::
44must have reference id:

```

## ts_minify_nested_enum_no_logical_assignment

```bash
thread 'thread 'tokio-runtime-worker' panicked at tokio-runtime-workercrates/rolldown/src/ast_scanner/mod.rs' panicked at :crates/rolldown/src/ast_scanner/mod.rs376::37644::
44must have reference id:

```

## ts_namespace_keep_names

```bash
called `Result::unwrap()` on an `Err` value: Transform failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                27,
                            ),
                            length: 14,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },
]

```

## ts_namespace_keep_names_target_es2015

```bash
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                27,
                            ),
                            length: 14,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },

```

ts_prefer_js_over_ts_inside_node_modules

## ts_print_non_finite_number_inside_with

- generate pure annotation
- inline enum value

## ts_sibling_enum

- generate pure annotation
- inline enum value

## ts_sibling_namespace

```bash
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Namespaces exporting non-const are not supported by Babel. Change to const or see: https://babeljs.io/docs/en/babel-plugin-transform-typescript",
            labels: Some(
                [
                    LabeledSpan {
                        label: None,
                        span: SourceSpan {
                            offset: SourceOffset(
                                80,
                            ),
                            length: 5,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Warning,
        },
    },

```

## ts_side_effects_false_warning_type_declarations

- snapshot not matched

## ts_this_is_undefined_warning

- snapshot not match

**Comment by Dunqing** [comment]
Can you retest these cases?  The `must have reference ID` error seems to have been resolved

**Comment by IWANABETHATGUY** [comment]
> Can you retest these cases? The `must have reference ID` error seems to have been resolved

Most of panic are gone, except these two: 
## enum_rules_from_type_script_5_0
```bash
 called `Result::unwrap()` on an `Err` value: Parse failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Expected `,` but found `Identifier`",
            labels: Some(
                [
                    LabeledSpan {
                        label: Some(
                            "`,` expected",
                        ),
                        span: SourceSpan {
                            offset: SourceOffset(
                                877,
                            ),
                            length: 2,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Error,
        },
    },
]
```
## export_type_issue379
```bash
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:67:21:
no entry found for key
``

**Comment by hyf0** [comment]
> ts_import_equals_tree_shaking_false
> the interesting thing is esbuild would eliminate unused variable even the treeshake is false

This is tsc's behavior. It's irrelevant with tree-shaking.
