### ISSUE TITLE
Should emit more meaningful diagnostic when meet unsupport module type

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1516]
## Reproduce
comment out https://github.com/sapphi-red/performance-compare/blob/83da84976034bde1d4dc3ee7151683c40cf31849/rolldown.config.mjs#L8
## Description
Currently, rolldown would emit unreadable error message when meet some unsupport module type, like **css**: 
```bash
Send should not fail: SendError { .. }Send should not fail: SendError { .. }thread 'thread '

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
tokio-runtime-workertokio-runtime-worker' panicked at ' panicked at thread 'crates/rolldown/src/module_loader/normal_module_task.rsthread 'crates/rolldown/src/module_loader/normal_module_task.rstokio-ru
ntime-worker:tokio-runtime-worker:' panicked at 237' panicked at 237crates/rolldown/src/module_loader/normal_module_task.rs:crates/rolldown/src/module_loader/normal_module_task.rs::8:8237:
237:
:Send should not fail: SendError { .. }:Send should not fail: SendError { .. }8thread '
8
:
tokio-runtime-worker:
Send should not fail: SendError { .. }' panicked at Send should not fail: SendError { .. }
crates/rolldown/src/module_loader/normal_module_task.rs
:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:thread '8tokio-runtime-worker:
' panicked at Send should not fail: SendError { .. }crates/rolldown/src/module_loader/normal_module_task.rs
thread ':tokio-runtime-worker237' panicked at :crates/rolldown/src/module_loader/normal_module_task.rs8::
237Send should not fail: SendError { .. }:
8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at ' panicked at crates/rolldown/src/module_loader/normal_module_task.rsthread 'crates/rolldown/src/module_loader/normal_module_task.rs
::tokio-runtime-worker237237' panicked at ::crates/rolldown/src/module_loader/normal_module_task.rs88::
:
237Send should not fail: SendError { .. }Send should not fail: SendError { .. }:

8:
Send should not fail: SendError { .. }
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at ' panicked at crates/rolldown/src/module_loader/normal_module_task.rscrates/rolldown/src/module_loader/normal_module_task.rs::237237
:thread ':88tokio-runtime-worker:
' panicked at :
Send should not fail: SendError { .. }crates/rolldown/src/module_loader/normal_module_task.rsSend should not fail: SendError { .. }
:
237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rsthread ':tokio-runtime-worker237' panicked at :crates/rolldown/src/module_loader/normal_module_task.rs8::
237Send should not fail: SendError { .. }:
8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/module_loader/normal_module_task.rs:237:8:
Send should not fail: SendError { .. }

 ERROR  Rolldown internal error: Parse failed, got [                                                                                                                                            23:08:59
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Expected in but found {",
            labels: Some(
                [
                    LabeledSpan {
                        label: Some(
                            "in expected",
                        ),
                        span: SourceSpan {
                            offset: SourceOffset(
                                6,
                            ),
                            length: 1,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Error,
        },
    },
]

  OxcDiagnostic {
  inner: OxcDiagnosticInner {
  message: "Expected in but found {",
  labels: Some(
  [
  LabeledSpan {
  label: Some(
  "in expected",
  ),
  span: SourceSpan {
  offset: SourceOffset(
  6,
  ),
  length: 1,
  },
  primary: false,
  },
  ],
  ),
  help: None,
  severity: Error,
  },
  },
  ] 

```

**Comment by IWANABETHATGUY** [comment]
Such error message is hard to distinguish for a developer,  not to mention a user.

**Comment by IWANABETHATGUY** [comment]
**Reproduce** 
comment out https://github.com/sapphi-red/performance-compare/blob/83da84976034bde1d4dc3ee7151683c40cf31849/rolldown.config.mjs#L8

**Comment by hyf0** [comment]
Mostly because calling `unwrap` or `expect` wrongly.

**Comment by IWANABETHATGUY** [comment]
yeah, btw we should emit diagnostic and gracefully shutdown the process.

**Comment by hyf0** [comment]
Self-assigned. I need to refactor the current load transform pipeline and will solve this issue too.

**Comment by IWANABETHATGUY** [comment]
I think the diagnostic message is good enough for now,  we could close it 
```bash
 ERROR  Rolldown internal error: "/Documents/rolldown-rs/rolldown/examples/basic-vue/test.css" is not specified module type,  rolldown can't handle this asset correctly. Please 
use the load/transform hook to transform the resource
```

**Comment by hyf0** [comment]
Nice.
