### ISSUE TITLE
rolldown@0.11.0  failed to run in stackblitz

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1547]
### Reproduction link or steps

https://stackblitz.com/edit/github-8ktkmp

### What is expected?

No error.

### What is actually happening?

```
(node:12) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

 ERROR  Cannot read properties of undefined (reading 'Info')                7:57:17 PM

  at bindingifyLogLevel (node_modules/rolldown/dist/shared/utils_index-DAvBTBzR.mjs:1190:56)
  at bindingifyInputOptions (node_modules/rolldown/dist/shared/utils_index-DAvBTBzR.mjs:1175:13)
  at Module.createBundler (node_modules/rolldown/dist/shared/utils_index-DAvBTBzR.mjs:1544:31)
  at async #getBundler (node_modules/rolldown/dist/shared/rolldown-RjvHfXoR.mjs:31:37)
  at async RolldownBuild.write (node_modules/rolldown/dist/shared/rolldown-RjvHfXoR.mjs:43:19)
  at async bundleInner (node_modules/rolldown/dist/esm/cli.mjs:645:23)
  at async bundle (node_modules/rolldown/dist/esm/cli.mjs:639:3)
  at async Object.run (node_modules/rolldown/dist/esm/cli.mjs:766:4)
  at async runCommand (node_modules/rolldown/dist/esm/cli.mjs:419:13)
  at async runMain (node_modules/rolldown/dist/esm/cli.mjs:519:4) 



 ERROR  Cannot read properties of undefined (reading 'Info')     
```

### System Info

```Shell
.
```

**Comment by hyf0** [comment]
@Brooooooklyn it seems to be a bug of new NAPI-RS.

![image](https://github.com/rolldown/rolldown/assets/49502170/85d4e509-7544-4682-9ebf-450c4911bf41)

This points to a wrong path.

**Comment by hyf0** [comment]
You could also reproduced it by cloneing https://github.com/rolldown/rolldown-starter-stackblitz to local and run `npm i --cpu=wasm32`.

I'm using `node@v20.13.1`

**Comment by Brooooooklyn** [comment]
> ![image](https://github.com/rolldown/rolldown/assets/3468483/b0d856b4-138a-4406-a766-f379da61c7f3)

I don't believe it's a bug of NAPI-RS.

First the Node.js wasi bundle test is passed, and I found there are `BindingPluginContext` and `Bundler` exist in the wasm exports. Maybe there are some issues on StackBlitz.

**Comment by Brooooooklyn** [comment]
Ok, I can reproduce it on my macOS, but it's weird it passed on CI

**Comment by hyf0** [comment]
> Ok, I can reproduce it on my macOS, but it's weird it passed on CI

Yeah. Me too. 

---

Off the topic. It would be cool if there is something like `webcontainer-node` so we could run CI using it :).
