### ISSUE TITLE
Wrong scope of top level bindings

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1743]
### Reproduction link or steps

.

### What is expected?

.

### What is actually happening?

```
---- test_tests__esbuild__default__require_without_call_inside_try__config_json stdout ----
Input: /Users/hyf/Documents/gh/rolldown/crates/rolldown/tests/esbuild/default/require_without_call_inside_try/_config.json
thread 'test_tests__esbuild__default__require_without_call_inside_try__config_json' panicked at crates/rolldown_testing/src/case/fixture.rs:163:29:
called `Result::unwrap()` on an `Err` value: Symbol ("aliasedRequire", SymbolId(1), 1) is declared in the top-level scope but doesn't get scanned by the scanner
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_tests__esbuild__default__var_relocating_bundle__config_json stdout ----
Input: /Users/hyf/Documents/gh/rolldown/crates/rolldown/tests/esbuild/default/var_relocating_bundle/_config.json
thread 'test_tests__esbuild__default__var_relocating_bundle__config_json' panicked at crates/rolldown_testing/src/case/fixture.rs:163:29:
called `Result::unwrap()` on an `Err` value: Symbol ("a", SymbolId(1), 1) is declared in the top-level scope but doesn't get scanned by the scanner

---- test_tests__esbuild__packagejson__test_package_json_browser_map_avoid_missing__config_json stdout ----
Input: /Users/hyf/Documents/gh/rolldown/crates/rolldown/tests/esbuild/packagejson/test_package_json_browser_map_avoid_missing/_config.json
thread 'test_tests__esbuild__packagejson__test_package_json_browser_map_avoid_missing__config_json' panicked at crates/rolldown_testing/src/case/fixture.rs:163:29:
called `Result::unwrap()` on an `Err` value: Symbol ("index", SymbolId(1), 1) is declared in the top-level scope but doesn't get scanned by the scanner


failures:
    test_tests__esbuild__default__require_without_call_inside_try__config_json
    test_tests__esbuild__default__var_relocating_bundle__config_json
    test_tests__esbuild__packagejson__test_package_json_browser_map_avoid_missing__config_json
```

### System Info

```Shell
.
```

**Comment by hyf0** [comment]
Founded after adding assertions in #1742.

**Comment by hyf0** [comment]
Regression on rollup tests:

failures [
  "rollup@function@catch-block-scope: uses correct scope in catch blocks",
  "rollup@function@catch-scope-variables: handles variable declarations in catch scopes",
  "rollup@function@vars-not-removed-in-if-block: preserves var declarations in if blocks (#1113)"
]
