### ISSUE TITLE
[Bug]: thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#2038]
### Reproduction link or steps

I'm testing Rolldown in https://github.com/oxc-project/monitor-oxc/tree/rolldown

I changed it to a local build

```
  "devDependencies": {
    "rolldown": "link:../../github/rolldown/packages/rolldown",
```

```
pnpm install
pnpm run rolldown
```

### What is expected?

No panic or more information about which file is panicking.

### What is actually happening?

```
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 168, symbol: SymbolId(115) }, original_name: "Parser"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 3422, symbol: SymbolId(4) }, original_name: "RULESET"
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 357, symbol: SymbolId(4) }, original_name: "Root"
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 2314, symbol: SymbolId(32) }, original_name: "eraseLines"
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 705, symbol: SymbolId(47) }, original_name: "Gzip"
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 4500, symbol: SymbolId(6549) }, original_name: "rollup"
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 2531, symbol: SymbolId(4) }, original_name: "DOCUMENT_MODE"
thread '<unnamed>' panicked at crates/rolldown/src/types/symbols.rs:68:7:
canonical name not found for SymbolRef { owner: 2240, symbol: SymbolId(7) }, original_name: "find"
```

### System Info

```Shell
None
```

**Comment by AliceLanniste** [comment]
hi,  I want to try it

**Comment by Boshen** [comment]
@IWANABETHATGUY can you take a look at this as well? I want to get `monitor-oxc` compiling 😅

**Comment by IWANABETHATGUY** [comment]
> @IWANABETHATGUY can you take a look at this as well? I want to get `monitor-oxc` compiling 😅

Sure, sorry @AliceLanniste , this issue has higher priority, I am gonna take over it.

**Comment by Boshen** [comment]
Note: it only breaks for dynamic imports, we may need more dynamic import tests 😅
