### ISSUE TITLE
[Bug]: Rolldown does not show the stacktrace when an error happened inside JS plugins

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2551]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss?file=package.json,rolldown.config.mjs
2. `npm i` and `npm run build` runs automatically
3. The error is shown

### What is expected?

The following error happens:
```
[!] (plugin foo) Error: throw!
src/entry.js
    at Object.transform (file:///home/projects/xoriwgqxmv.github/rolldown.config.mjs:24:15)
    at eval (/home/.npm/_npx/1ee1cf83ded2a161/node_modules/rollup/dist/shared/rollup.js:1087:40)
    at <anonymous> (https://xoriwgqxmvgithub-1r5y.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:22847)
```

It does not have to be the same. The important points are

- show which plugin failed
- show the stacktrace
- show the processing file when that error happened

### What is actually happening?

The following error happens:
```
[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
GenericFailure, Error: throw!

[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
GenericFailure, Error: throw!

Error: Build failed
    at napi_create_error (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:4535:25)
    at eval (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1283:58)
    at NodeEnv.callIntoModule (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:639:19)
    at NodeEnv.callbackIntoModule (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:758:21)
    at f (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1277:37)
    at Object.dispatchOne (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1305:29)
    at Object.dispatch (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1321:43)
    at Worker.handler (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:864:40) {
  code: 'GenericFailure'
}
```

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@6aa4503 => 0.13.2
```

**Comment by ikkz** [comment]
I encountered the same issue when migrating from Rollup to Rolldown. I couldn't identify which Rollup plugin was causing the problem, making it difficult to make the necessary adjustments. If this issue could be resolved, the migration experience would be much smoother.

```
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: Rolldown internal error: GenericFailure, TypeError: Cannot read properties of null (reading 'importedIds')] {
  code: 'GenericFailure'
}

Node.js v22.10.0
```

**Comment by hyf0** [comment]
Some notes:
I suspect this is because rolldown drops the original error. Maybe `Error#cause` property could help with this issue. Need more invesigation. @Brooooooklyn cc

**Comment by hyf0** [comment]
Solved by https://github.com/rolldown/rolldown/issues/2551.

**Comment by hi-ogawa** [comment]
Hmm, unfortunately the PR only handled `resolveId`. Other hooks like `load` and `transform` seems to still absorb js errors in different places.

- load

```ts
[UNLOADABLE_DEPENDENCY] Error: Could not load index.ts - GenericFailure, Error: boom.

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: Build failed] { code: 'GenericFailure' }
```

- transform

```sh
[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
GenericFailure, Error: boom

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: Build failed] { code: 'GenericFailure' }
```

I should've made sure by adding more tests :cry: Should we re-open?
