### ISSUE TITLE
[Bug]: Can't use virtual module as entry

### ISSUE THREAD

**Issue by ikkz** [rolldown/rolldown#2659]
### Reproduction link or steps

https://stackblitz.com/edit/github-u5i1ag?file=rolldown.config.mjs

### What is expected?

works like rollup
```
❯ npm run upbuild

> upbuild
> rollup -c rolldown.config.mjs


test → dist...
(node:56) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
created dist in 12ms
```

### What is actually happening?

```
❯ npm run build

> build
> RD_LOG=error rolldown -c ./rolldown.config.mjs

(node:59) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Rolldown internal error: file name contained an unexpected NUL byte
    at napi_create_error (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:4535:25)
    at f/< (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1283:58)
    at callIntoModule (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:639:21)
    at callbackIntoModule (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/runtime/dist/emnapi.cjs.js:758:21)
    at f (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1277:37)
    at dispatchOne (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1305:29)
    at dispatch (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1321:43)
    at handler (/home/projects/xoriwgqxmv.github/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:864:40)
    at emit (node:events:30:11015)
    at internal/worker/Worker/</< (node:internal/worker:281:4175)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:102:8637)
    at internal/per_context/messageport/t.emitMessage (node:internal/per_context/messageport:169:364)
    at _0x30c206</start/_0x512fcf/< (https://xoriwgqxmvgithub-1r5y.w-corp-staticblitz.com/blitz.f565b097.js:40:878355)
    at _0x27d866/< (https://xoriwgqxmvgithub-1r5y.w-corp-staticblitz.com/blitz.f565b097.js:40:198039)
    at _0x7bfab (https://xoriwgqxmvgithub-1r5y.w-corp-staticblitz.com/blitz.f565b097.js:40:198143)
    at _0x512fcf (https://xoriwgqxmvgithub-1r5y.w-corp-staticblitz.com/blitz.f565b097.js:40:878262) {
  code: 'GenericFailure'
}

Node.js v18.20.3
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: latest => 0.14.0
```

**Comment by hyf0** [comment]
Try not use `\0` convention. I guess this problem is still related to #1115. @Brooooooklyn cc
