### ISSUE TITLE
[Feature Request]: Compatible with `rollup-plugin-dts`

### ISSUE THREAD

**Issue by sxzz** [rolldown/rolldown#3047]
### Reproduction link or steps

https://stackblitz.com/edit/github-v7esq4?file=rolldown.config.mjs

### What is expected?

Works without errors.

### What is actually happening?

```
Error: Build failed with 1 error:
Error: [EXPORT_UNDEFINED_VARIABLE] Error: `foo` is not declared in this file
   ╭─[src/main.ts:3:10]
   │
 3 │ export { foo };
   │          ─┬─  
   │           ╰─── 
───╯


    at normalizeErrors (file:///home/projects/github-v7esq4/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:128:18)
    at handleOutputErrors (file:///home/projects/github-v7esq4/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:264:34)
    at transformToRollupOutput (file:///home/projects/github-v7esq4/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:258:2)
    at RolldownBuild.write (file:///home/projects/github-v7esq4/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:2690:10)
    at async bundleInner (file:///home/projects/github-v7esq4/node_modules/rolldown/dist/esm/cli.mjs:388:23) {
  errors: [Getter/Setter]
}
```

### System Info

```Shell
N/A
```

**Comment by IWANABETHATGUY** [comment]
after `rollup-plugin-dts` transformation, it return such result: 
```js
generateDtsFromTs():  {
  code: 'declare const a = 100;\n\nexport { a };\n',
  ast: {
    type: 'Program',
    sourceType: 'module',
    body: [ [Object], [Object] ],
    start: 0,
    end: 38
  },
  map: SourceMap {
    version: 3,
    file: undefined,
    sources: [ '' ],
    sourcesContent: undefined,
    names: [],
    mappings: 'AAAO;'
  }
}
```
and because the file extension is `ts`, rolldown wll use oxc to transpile the file into `js` which removes the first `declare const a` stmt.

**Comment by IWANABETHATGUY** [comment]
I think it is hard to reuse `rollup-plugin-dts` in rolldown until we can handle the `ts` syntax ourselves.

**Comment by IWANABETHATGUY** [comment]
https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.ts%00declare+const+test+%3D+1000%3B%0Aexport+%7Bconst%7D%3B&b=%00pacakge.json%00&o=%7B%0A++treeShaking%3A+true%2C%0A+format%3A+%22esm%22%2C%0A%22bundle%22%3A+true%2C%0A%22outdir%22%3A+%22dist%22%2C%0Aloader%3A+%7B%22.ts%22%3A+%22copy%22%7D%0A%0A%7D, maybe it is possible when we support `copy` loader?

**Comment by hyf0** [comment]
It can't be supported due to the nature of `rollup-plugin-dts`. It rely on rollup's internal implementation while rolldown choose a different one.

That's why we have a #1388 try to implement it natively. I'm gonna mark this issue as wontfix. But feedbacks are still welcome.

**Comment by IWANABETHATGUY** [comment]
Yeah, this requires a lot of work to make our arch with opt-in Ts Syntax aware ability, so we could preserve the ts syntax as is, we don't have enough bandwidth to do this for now, maybe we will support this in the long run.

**Comment by ArthurDarkstone** [comment]
how can i generate 'dts' like this with rolldown 🫡?

```
output: [
    { file: `${fn}.d.cts` },
    { file: `${fn}.d.mts` },
    { file: `${fn}.d.ts` }, // for node10 compatibility
  ],
```

**Comment by sxzz** [comment]
FYI: I'm creating https://github.com/sxzz/rolldown-plugin-dts for bundling dts on Rolldown.

**Comment by sxzz** [comment]
https://github.com/sxzz/rolldown-plugin-dts is now pretty stable and will soon be integrated as a built-in plugin.
