### ISSUE TITLE
[Bug]: Fails to run in Bun

### ISSUE THREAD

**Issue by Malien** [rolldown/rolldown#3139]
### Reproduction link or steps

This is probably not the priority of the team, but bun can't run the current build of rolldown. https://github.com/Malien/rolldown-is-broken-in-bun.

This is likely a bun bug ¯\\\_(ツ)_/¯ 

```js
import { rolldown } from "rolldown"

const build = await rolldown({ input: ["./sample.mjs"] });
try {
    await build.generate()
} finally {
    await build.close()
}
```

```sh
❯ bun build.mjs

```

### What is expected?

Welp. Not the crash.

### What is actually happening?

```
75 |                    summary += "\n...";
76 |                    break;
77 |            }
78 |            summary += getErrorMessage(errors[i]) + "\n";
79 |    }
80 |    const wrapper = new Error(summary);
                      ^
error: Build failed with 1 error:
Error: UNKNOWN_RETURN_VALUE. Cannot convert unknown to `Option<String>` in Arc<ThreadsafeFunction<RenderedChunk, Either<Either<Promise<Option<String>>, Option<Str
ing>>, UnknownReturnValue>, RenderedChunk, false, true>>.
    at get errors (native)
    at handleOutputErrors (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:215:20)
    at transformToRollupOutput (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:210:2)

 errors: [
  {
    "code": "InvalidArg",
    "originalLine": 207,
    "originalColumn": 27
  }
]

      at normalizeErrors (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:80:18)
      at handleOutputErrors (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:216:34)
      at transformToRollupOutput (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:210:2)

Bun v1.1.38 (macOS arm64)
```

### System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M2
    Memory: 177.41 MB / 24.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 23.4.0 - ~/.local/share/mise/installs/node/23.4.0/bin/node
    npm: 10.9.2 - ~/.local/share/mise/installs/node/23.4.0/bin/npm
    pnpm: 9.12.3 - ~/.local/share/mise/installs/node/23.4.0/bin/pnpm
    bun: 1.1.38 - /opt/homebrew/bin/bun
    Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.109
    Chrome Canary: 133.0.6891.0
    Safari: 18.1
    Safari Technology Preview: 18.0
  npmPackages:
    rolldown: ^0.15.0 => 0.15.0 


Bun version `1.1.38`
```

### Any additional comments?

Curiously deno works fine

**Comment by Boshen** [comment]
This should be reported to Bun per Bun's policy of reporting node.js compatibility bugs if I remember correctly.
