### ISSUE TITLE
[Bug]: Error: [EXPORT_UNDEFINED_VARIABLE] Error: `xxx` is not declared in this file

### ISSUE THREAD

**Issue by ArthurDarkstone** [rolldown/rolldown#3236]
### Reproduction link or steps

```
import json from '@rollup/plugin-json'

// ... some configs 


      input,
      output,
      plugins: [
        json() as RolldownPlugin,
      ],
```

### What is expected?

build success

### What is actually happening?

outputs

```
 vueuse  pnpm run build

> @vueuse/monorepo@12.2.0 build D:\Projects\github\forks\vueuse
> nr update && pnpm -r run build


> @vueuse/monorepo@12.2.0 update D:\Projects\github\forks\vueuse
> nr -C packages/metadata update && tsx scripts/update.ts


> @vueuse/metadata@12.2.0 update D:\Projects\github\forks\vueuse\packages\metadata
> tsx scripts/update.ts

No types dist found, run `npm run build:types` first.
Scope: 11 of 12 workspace projects
packages/metadata build$ rolldown --config=rolldown.config.ts
│ Error: Build failed with 8 errors:                                                                                                                                                                       
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `metadata` is not declared in this file
│     ╭─[metadata.ts:13:10]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │          ────┬───
│     │              ╰─────
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `functions` is not declared in this file
│     ╭─[metadata.ts:13:20]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };                                                            
│     │                    ────┬────
│     │                        ╰────── 
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `packages` is not declared in this file
│     ╭─[metadata.ts:13:31]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │                               ────┬───
│     │                                   ╰─────
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `categories` is not declared in this file
│     ╭─[metadata.ts:13:41]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │                                         ─────┬────
│     │                                              ╰──────
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `functionNames` is not declared in this file
│     ╭─[metadata.ts:13:53]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │                                                     ──────┬──────
│     │                                                           ╰────────
│ ────╯
│ ...
│     at normalizeErrors (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:79:18)
│     at handleOutputErrors (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:230:34)
│     at transformToRollupOutput (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:224:2)
│     at RolldownBuild.write (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:2706:10)
│     at async bundleInner (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/esm/cli.mjs:445:17)
│     at async bundleWithConfig (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/esm/cli.mjs:365:6)
│     at async main (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/esm/cli.mjs:2004:3) {
│   errors: [Getter/Setter]
│ }
└─ Failed in 3.2s at D:\Projects\github\forks\vueuse\packages\metadata
packages/shared build$ rolldown --config=rolldown.config.ts
└─ Running...
D:\Projects\github\forks\vueuse\packages\metadata:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vueuse/metadata@12.2.0 build: `rolldown --config=rolldown.config.ts`
Exit status 1
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 15.00 GB / 31.74 GB
  Binaries:
    Node: 20.18.0 - ~\AppData\Local\pnpm\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.8.2 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 9.15.1 - D:\Projects\github\forks\vueuse\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.105)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    rolldown: 1.0.0-beta.1 => 1.0.0-beta.1
```

**Comment by ArthurDarkstone** [comment]
https://github.com/vueuse/vueuse/pull/4434

**Comment by IWANABETHATGUY** [comment]
try to remove `json` plugin, since rolldown has builtin support json, they have similar transform output

**Comment by ArthurDarkstone** [comment]
> try to remove `json` plugin, since rolldown has builtin support json, they have similar transform output

thanks, but still got same error 

change:

```
      input,
      output,
      plugins: [
        // esbuild({ target: 'es2018' }) as RolldownPlugin,
        // try to remove json()
        // json() as RolldownPlugin,
        pluginPure as RolldownPlugin,
      ],
      external: [
        ...externals,
        ...(external || []),
      ],
```

run `pnpm build`

output: 

```
 vueuse  pnpm run build

> @vueuse/monorepo@12.2.0 build D:\Projects\github\forks\vueuse
> nr update && pnpm -r run build


> @vueuse/monorepo@12.2.0 update D:\Projects\github\forks\vueuse
> nr -C packages/metadata update && tsx scripts/update.ts


> @vueuse/metadata@12.2.0 update D:\Projects\github\forks\vueuse\packages\metadata
> tsx scripts/update.ts

No types dist found, run `npm run build:types` first.
Scope: 11 of 12 workspace projects
packages/metadata build$ rolldown --config=rolldown.config.ts
│ Error: Build failed with 8 errors:                                                                                                                                                                       
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `metadata` is not declared in this file
│     ╭─[metadata.ts:13:10]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │          ────┬───
│     │              ╰─────
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `functions` is not declared in this file
│     ╭─[metadata.ts:13:20]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };                                                            
│     │                    ────┬────
│     │                        ╰────── 
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `packages` is not declared in this file
│     ╭─[metadata.ts:13:31]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │                               ────┬───
│     │                                   ╰─────
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `categories` is not declared in this file
│     ╭─[metadata.ts:13:41]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │                                         ─────┬────
│     │                                              ╰──────
│ ────╯
│ Error: [EXPORT_UNDEFINED_VARIABLE] Error: `functionNames` is not declared in this file
│     ╭─[metadata.ts:13:53]
│     │
│  13 │ export { metadata, functions, packages, categories, functionNames, categoryNames, coreCategoryNames, addonCategoryNames, getFunction };
│     │                                                     ──────┬──────
│     │                                                           ╰────────
│ ────╯
│ ...
│     at normalizeErrors (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:79:18)
│     at handleOutputErrors (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:230:34)
│     at transformToRollupOutput (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:224:2)
│     at RolldownBuild.write (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:2706:10)
│     at async bundleInner (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/esm/cli.mjs:445:17)
│     at async bundleWithConfig (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/esm/cli.mjs:365:6)
│     at async main (file:///D:/Projects/github/forks/vueuse/node_modules/.pnpm/rolldown@1.0.0-beta.1_@babel+runtime@7.21.5/node_modules/rolldown/dist/esm/cli.mjs:2004:3) {
│   errors: [Getter/Setter]
│ }
└─ Failed in 2.6s at D:\Projects\github\forks\vueuse\packages\metadata
packages/shared build$ rolldown --config=rolldown.config.ts
└─ Running...
D:\Projects\github\forks\vueuse\packages\metadata:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vueuse/metadata@12.2.0 build: `rolldown --config=rolldown.config.ts`
Exit status 1
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ArthurDarkstone** [comment]
> try to remove `json` plugin, since rolldown has builtin support json, they have similar transform output

maybe there is some error with `json` to `esm` transform

**Comment by ArthurDarkstone** [comment]
> try to remove `json` plugin, since rolldown has builtin support json, they have similar transform output

Found the root cause of the problem, the reason is the use of another plugin `rollup-plugin-dts`

https://github.com/rolldown/rolldown/issues/3047
