### ISSUE TITLE
[Bug]: unable to inline type imports

### ISSUE THREAD

**Issue by ThatOneCalculator** [rolldown/rolldown#3244]
### Reproduction link or steps

This does not work:

```ts
import { type Component, type Ref, markRaw, ref } from "vue";
```

But this does:

```ts
import { markRaw, ref } from "vue";
import type { Component, Ref } from "vue";
```

### What is expected?

`import { type Component, type Ref, markRaw, ref } from "vue";` to work, as it does in upstream Vite/Rollup

### What is actually happening?

Interestingly, I get two different errors from Firefox and Chromium

Chromium:

```
Uncaught SyntaxError: Unexpected identifier 'Component'
```

Firefox:

```
SyntaxError: missing '}' after module specifier list
```

### System Info

```Shell
System:
    OS: Linux 6.13 Arch Linux
    CPU: (24) x64 AMD Ryzen AI 9 HX 370 w/ Radeon 890M
    Memory: 20.01 GB / 30.47 GB
    Container: Yes # this tool said yes for some reason, but it's bare metal
    Shell: 3.7.1 - /usr/bin/fish
  Binaries:
    Node: 23.5.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 11.0.0 - /usr/bin/npm
    pnpm: 9.15.1 - /usr/bin/pnpm
    bun: 1.1.42 - ~/.bun/bin/bun
  Browsers:
    Chromium: 131.0.6778.204
    Firefox: Mozilla Firefox 133.0.3
```

### Any additional comments?

Using Bun and `rolldown/vite@a839caa`

**Comment by IWANABETHATGUY** [comment]
Can you provide us with a reproduce repo?

**Comment by ThatOneCalculator** [comment]
I can't make a minimal reproduction -- it seemingly has to do with a specific package or piece of code, but the errors printed are not helpful.

**Comment by ThatOneCalculator** [comment]
@IWANABETHATGUY sorry for that deleted comment (was meant for the other issue) -- here's my repro: https://github.com/ThatOneCalculator/vite-rolldown-issue-repro

https://github.com/ThatOneCalculator/vite-rolldown-issue-repro/blob/972a1c0c805b5aa04d7c27c78e3ca640ac5f796e/src/App.vue#L4

```
$ vite build
vite v6.0.6 building for production...
The built-in minifier is still under development. Setting "minify: true" is not recommended for production use.
✓ 13 modules transformed.
x Build failed in 209ms
error during build:
Build failed with 1 error:
Error: [PARSE_ERROR] Error: Expected `,` but found `Identifier`
   ╭─[src/App.vue?vue&type=script&setup=true&lang.ts:7:20]
   │
 7 │ import { ref, type Ref } from "vue";
   │                    ─┬─  
   │                     ╰─── `,` expected
───╯


    at normalizeErrors (file:///home/kainoa/Git/vite-rolldown-issue-repro/node_modules/rolldown/dist/shared/src-B74WDvF2.mjs:79:18)
    at handleOutputErrors (file:///home/kainoa/Git/vite-rolldown-issue-repro/node_modules/rolldown/dist/shared/src-B74WDvF2.mjs:230:34)
    at transformToRollupOutput (file:///home/kainoa/Git/vite-rolldown-issue-repro/node_modules/rolldown/dist/shared/src-B74WDvF2.mjs:224:2)
    at RolldownBuild.write (file:///home/kainoa/Git/vite-rolldown-issue-repro/node_modules/rolldown/dist/shared/src-B74WDvF2.mjs:2706:10)
    at async buildEnvironment (file:///home/kainoa/Git/vite-rolldown-issue-repro/node_modules/vite/dist/node/chunks/dep-DJWglIpD.js:48763:16)
    at async Object.defaultBuildApp [as buildApp] (file:///home/kainoa/Git/vite-rolldown-issue-repro/node_modules/vite/dist/node/chunks/dep-DJWglIpD.js:49201:5)
    at async CAC.<anonymous> (file:///home/kainoa/Git/vite-rolldown-issue-repro/node_modules/vite/dist/node/cli.js:853:7)
error: script "build" exited with code 1
```

**Comment by IWANABETHATGUY** [comment]
This seems to be an issue related to `@vitejs/plugin-vue` plugin, the `moduleType` should be set to `ts` when `lang` attribute is marked as `ts`

**Comment by IWANABETHATGUY** [comment]
@underfin, @sapphi-red  maybe you guys know this better than me.

**Comment by underfin** [comment]
@ThatOneCalculator The `@vitejs/plugin-vue` integrated rolldown-vite version is `https://pkg.pr.new/@vitejs/plugin-vue@c794c24`, you should using it to avoid `PARSE_ERROR`. The publish version come from https://github.com/vitejs/vite-plugin-vue/actions/runs/12407252662/job/34636986573.

The original issue is come from oxc transformed typescript with `onlyRemoveTypeImports` has bugs. I'm try to fixed it.

**Comment by sapphi-red** [comment]
Yeah, it seems to be a bug in oxc.
```js
import { transform } from 'rolldown/experimental'

const result = transform('foo.ts', 'import { ref, type Ref } from "vue";', {
  typescript: {
    onlyRemoveTypeImports: true,
  },
})
console.log(result.code) // import { ref, type Ref } from "vue";
```
The output should be `import { ref } from "vue";` (related https://github.com/babel/babel/issues/15348)

**Comment by ThatOneCalculator** [comment]
Should this be reported to oxc?
