### ISSUE TITLE
[Bug]: rolldown -c -w parse -w as config

### ISSUE THREAD

**Issue by phk422** [rolldown/rolldown#3248]
### Reproduction link or steps

Repo: https://github.com/phk422/rolldown-demo
Running [pnpm dev](https://github.com/phk422/rolldown-demo/blob/76b9430664789c5c5f5908785a1e6329feff6e62/package.json#L8) works fine.
However, running [pnpm dev2](https://github.com/phk422/rolldown-demo/blob/76b9430664789c5c5f5908785a1e6329feff6e62/package.json#L9) results in an error.

### What is expected?

The rolldow.config configuration can be correctly identified using pnpm dev2

### What is actually happening?

The following error occurs with pnpm dev2:

```bash
> rolldown -c -w

Error: Error happened while loading config.
    at loadConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:352:9)
    at bundleWithConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:359:23)
    ... 4 lines matching cause stack trace ...
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15) {
  [cause]: Error: Unsupported config format. Expected: `.js,.mjs,.cjs,.ts,.mts,.cts` but got ``
      at loadConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:350:12)
      at bundleWithConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:359:23)
      at main (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:2004:9)
      at file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:2017:1
      at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
      at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 13.07 GB / 31.83 GB
  Binaries:
    Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.33.6 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.2989
  npmPackages:
    rolldown: 1.0.0-beta.1 => 1.0.0-beta.1
```

**Comment by underfin** [comment]
It is caused by not supporting the auto research config file in cwd. The rollup/vite also has the feature at cli, i think maybe we should support it.

**Comment by shulaoda** [comment]
The `parseArgs` in Node.js causes the command `-c -w` to be incorrectly interpreted as `c: "-w"`. We may need to use a different command-line parsing tool or implement a more complex adaptation.

**Comment by IWANABETHATGUY** [comment]
Seems not easy to solve

**Comment by phk422** [comment]
> Seems not easy to solve

Due to the limitations of the parseArgs function, to solve this problem, it may be necessary to reconstruct the cli parameter parsing code.

**Comment by IWANABETHATGUY** [comment]
I recommend using `rolldown -w -c` instead. The current usage is quite niche and can be worked around with minimal effort. We utilize the built-in `parseArgs` to minimize the size of the `rolldown` distributed package, so introducing another argument parser package may not be justified for this specific use case.

**Comment by nstepien** [comment]
Sorry to comment on an old issue, but we use rolldown via an npm script:
```
  "scripts": {
    "build": "rolldown -c",
```
so `npm run build` is used to build with rolldown,
but if I try to enable the watch flag  with `npm run build -- --watch` then the process errors out as described above.
Of course I can add a separate `build:watch` script, or run `npx rolldown ...` instead, but it can be inconvenient.

**Comment by h-a-n-a** [comment]
> Sorry to comment on an old issue, but we use rolldown via an npm script:
> 
> ```
>   "scripts": {
>     "build": "rolldown -c",
> ```
> 
> so `npm run build` is used to build with rolldown, but if I try to enable the watch flag with `npm run build -- --watch` then the process errors out as described above. Of course I can add a separate `build:watch` script, or run `npx rolldown ...` instead, but it can be inconvenient.

Thanks for the report! We will fix this issue in our CLI migration.
