### ISSUE TITLE
[Bug]: allow functions as values for `assetFileNames`

### ISSUE THREAD

**Issue by skryukov** [rolldown/rolldown#3253]
### Reproduction link or steps

[`output.assetFileNames`](https://rollupjs.org/configuration-options/#output-assetfilenames) configuration option is ignored by Rolldown. Also note that unlike Rollup, it doesn't allow passing function, only a string.

```js
import { defineConfig } from "rolldown";
import css from "rollup-plugin-import-css";

export default defineConfig({
  input: ['./src/entry.js', './src/other-entry.js'],
  output: {
    assetFileNames: "my.css",
    // assetFileNames: () => "my.css",
  },
  plugins: [css()],
});
```

Repro: https://stackblitz.com/~/edit/github-8tvmh5ew

Commands:
- Rolldown build: `npm run build`
- Rollup build: `npm run buildup`

### What is expected?

1. I expect Rolldown to respect `assetFileNames: "my.css"` option and rename asset from `entry.css` to `my.css`.
2. I expect Rolldown to allow functions as values for `assetFileNames`.

### What is actually happening?

For `assetFileNames: "my.css"` Rolldown just renders `entry.css`.

For `assetFileNames: () => "my.css"` Rolldown raises an error:

```
rolldown --config ./rolldown.config.js

Error: Failed to convert JavaScript value `function assetFileNames(..) ` into rust type `String` on BindingOutputOptions.assetFileNames on BindingBundlerOptions.outputOptions
    at createBundler (.../node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:2673:13)
    at async #getBundlerWithStopWorker (.../node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:2696:26)
    at async RolldownBuild.write (.../node_modules/rolldown/dist/shared/src-Bb3zZkPW.mjs:2704:23)
    at async bundleInner (.../node_modules/rolldown/dist/esm/cli.mjs:445:17)
    at async bundleWithConfig (.../node_modules/rolldown/dist/esm/cli.mjs:365:6)
    at async main (.../node_modules/rolldown/dist/esm/cli.mjs:2004:3) {
  code: 'StringExpected'
}
```

### System Info

```Shell
Binaries:
    Node: 20.12.1 - ~/.asdf/installs/nodejs/20.12.1/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.12.1/bin/yarn
    npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.12.1 - ~/.asdf/installs/nodejs/20.12.1/bin/pnpm
    bun: 1.1.21 - ~/.bun/bin/bun
  npmPackages:
    rolldown: ^1.0.0-beta.1 => 1.0.0-beta.1
```

**Comment by shulaoda** [comment]
You should use below options:
```js
cssEntryFileNames?: string | ChunkFileNamesFunction
cssChunkFileNames?: string | ChunkFileNamesFunction
```

**Comment by hyf0** [comment]
> - I expect Rolldown to respect assetFileNames: "my.css" option and rename asset from entry.css to my.css.

Rolldown supports bundling css itself. And we have

```
cssEntryFileNames?: string | ChunkFileNamesFunction
cssChunkFileNames?: string | ChunkFileNamesFunction
```

to control namings for emitted css assets.

> - I expect Rolldown to allow functions as values for assetFileNames.

I'm not familiar with its function usage. And we currently don't have plan for support this.

---

So far you should consider using rolldown as pure js/ts bundler. Css-related stuffs is considering as experimental and we are trying to stablize it. Bug reports are welcome, however, we don't have bandwidth to handle it case by case.

**Comment by phil294** [comment]
This can happen if you conditionally return `undefined` from `assetFileNames`. Had a bug in my Vite config, returning something useful fixed it here.
