### ISSUE TITLE
[Bug]: Rolldown produce wrong exports for UMD bundle

### ISSUE THREAD

**Issue by ceifa** [rolldown/rolldown#3269]
### Reproduction link or steps

I'm replacing a very simple rollup usage with rolldown. This is the replacement PR:
https://github.com/ceifa/wasmoon/pull/129

This is my tests failing because of the problem:
https://github.com/ceifa/wasmoon/actions/runs/12516854002/job/34916646245?pr=129

### What is expected?

Rolldown output should produce correct exports.

### What is actually happening?

Importing the output file from rolldown gives an "Null module" import error.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 5.29 GB / 7.72 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    Yarn: 1.22.22 - /mnt/c/Program Files/nodejs/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
    pnpm: 9.15.2 - /mnt/c/Program Files/nodejs/pnpm
    bun: 1.1.29 - /mnt/c/Users/ceifa/AppData/Roaming/npm/bun
```

### Any additional comments?

Diff between rollup and rolldown output: https://www.diffchecker.com/hcnlncBp/

**Comment by shulaoda** [comment]
It seems that `LuaFactory` is a class explicitly exported from `./factory`, but we defined it as `externalLiveBindings`:

```js
Object.defineProperty(exports, 'LuaFactory', {
  enumerable: true,
  get: function () {
    return LuaFactory;
  }
});
```

**Comment by shulaoda** [comment]
- Fix `define([exports], factory)` to `define(['exports'], factory)`
- Remove `import.meta.url` in `umd` format

**Comment by hyf0** [comment]
> * Fix `define([exports], factory)` to `define(['exports'], factory)`
> * Remove `import.meta.url` in `umd` format

`import.meta.url` should be polyfill if possible.

**Comment by underfin** [comment]
The rollup `import.meta.filename/dirname`
- non-esm format:  rewrite `undefined` 
- esm: preserve

The rolldown `import.meta.filename/dirname` is pollyfill to `__filename/__dirname` at `format: cjs ` and `platform: node`.

The rollup `import.meta.url`
- cjs:  [see here](https://rollupjs.org/repl/?version=4.28.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGIlMkMlMjBiYiUyQyUyMGJiYiUyMCU3RCUyMGZyb20lMjAnLiUyRmxpYi5qcyclM0IlNUNuY29uc29sZS5sb2coYiUyQyUyMGJiJTJDJTIwYmJiKSU1Q25leHBvcnQlMjBjb25zdCUyMGMlMjAlM0QlMjBpbXBvcnQubWV0YS51cmwlNUNuZXhwb3J0JTIwY29uc3QlMjBjYyUyMCUzRCUyMGltcG9ydC5tZXRhLmZpbGVuYW1lJTVDbmV4cG9ydCUyMGNvbnN0JTIwY2NjJTIwJTNEJTIwaW1wb3J0Lm1ldGEuZGlybmFtZSU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYiUyMCUzRCUyMGltcG9ydC5tZXRhLnVybCU1Q25leHBvcnQlMjBjb25zdCUyMGJiJTIwJTNEJTIwaW1wb3J0Lm1ldGEuZmlsZW5hbWUlNUNuZXhwb3J0JTIwY29uc3QlMjBiYmIlMjAlM0QlMjBpbXBvcnQubWV0YS5kaXJuYW1lJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJleHBvcnRzJTIyJTNBJTIybmFtZWQlMjIlMkMlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlN0QlN0QlN0Q=)
- esm: preserve

The rolldown `import.meta.url` is pollyfill to `require('url').pathToFileURL(__filename).href` at `format: cjs ` and `platform: node`.


But the sematic is not correct for rollup/rolldown, because the files is bundled, the user need to using `resolveImportMeta` to custome it at rollup. We need to find a way to resolve it at rolldown.

**Comment by underfin** [comment]
@ceifa The `import { LuaFactory } from '../dist/index.js'` is caused by you add `"type": "module"` at `package.json`, the test is ok after removed it.

**Comment by shulaoda** [comment]
> [@ceifa](https://github.com/ceifa) The `import { LuaFactory } from '../dist/index.js'` is caused by you add `"type": "module"` at `package.json`, the test is ok after removed it.

He added it because of the following in `rolldown.cnfig.js`:
```
(node:2348) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Error happened while loading config.
    at loadConfig (file:///home/runner/work/wasmoon/wasmoon/node_modules/rolldown/dist/esm/cli.mjs:352:9)
    at async bundleWithConfig (file:///home/runner/work/wasmoon/wasmoon/node_modules/rolldown/dist/esm/cli.mjs:359:[17](https://github.com/shulaoda/wasmoon/actions/runs/12628668921/job/35185171172#step:8:18))
    at async main (file:///home/runner/work/wasmoon/wasmoon/node_modules/rolldown/dist/esm/cli.mjs:2004:3) {
  [cause]: /home/runner/work/wasmoon/wasmoon/rolldown.config.js:1
  import copy from 'rollup-plugin-copy'
  ^^^^^^
  
  SyntaxError: Cannot use import statement outside a module
```

I removed it and replaced it with `rolldown.config.mjs`, but we still seem to need to resolve the` import.meta` polyfill issue.

See https://github.com/shulaoda/wasmoon/actions/runs/12628733519/job/35185348195?pr=1

**Comment by underfin** [comment]
Ok. That's need to polyfill `import.meta` related things.

**Comment by hyf0** [comment]
@ceifa  Since rollup replace them with `undefined`, you could now use the `define` option to do the same thing. We are still evaluating what's the best way to follow rollup's behavior

**Comment by underfin** [comment]
@ceifa We discuss the polyfill `import.meta` for `umd` format, the rolldown will give a warning for it, it will hasn't polyfill for it. I look into your use case, you generate `umd` format for the browser and nodejs usage, we recommend you generate `esm/cjs` for different usage. 
If you want to using `umd` format for it, it need to polyfill it by yourself (using https://github.com/rolldown/rolldown/issues/3269#issuecomment-2572639306).

**Comment by ceifa** [comment]
> [@ceifa](https://github.com/ceifa) We discuss the polyfill `import.meta` for `umd` format, the rolldown will give a warning for it, it will hasn't polyfill for it.

That is okay. I thought rolldown could be a drop-in replacement for rollup, but I can polyfill it myself, no problem.

For those who may find this issue in the future, that is the polyfill:

```js
define: {
    'import.meta.url': `(typeof document === 'undefined' && typeof location === 'undefined' ? require('u' + 'rl').pathToFileURL(__filename).href : typeof document === 'undefined' ? location.href : (_documentCurrentScript && _documentCurrentScript.src || new URL('index.js', document.baseURI).href))`
}
```

> we recommend you generate esm/cjs for different usage.

Actually I generate `umd` mostly to get also a iife out of the box. But I will find a way to generate the esm with iife. Open to suggestions too.
